### ISSUE TITLE
main.styl

### ISSUE THREAD

**Issue by shevdi** [clicktronix/testsummary.github.io#2]
В main.styl лежат еще стили, которые стоило бы перенести в компоненты. Особенно блоки. Хорошо, когда все стили для одной компоненты лежат в одном месте, что бы было легче читать код. При необходимости можно передавать вниз переменные, которые объявлять уже в main.styl или в отдельном файле - обычно его называют variables.
Можно объявить один самый используемый шрифт на html, а где надо уже переопределять.

**Comment by clicktronix** [comment]
Разобрал полностью main.styl, оставил только заголовок. Шрифты оставил как были, все практически одинаково юзаются.
