### ISSUE TITLE
Переда данных

### ISSUE THREAD

**Issue by shevdi** [clicktronix/testsummary.github.io#3]
В реальном приложении заголовки вполне вероятно были бы жестко прописаны в html. А вот сам текст Lorem ipsum подгружался бы из базы данных. Но в этом случае можно просто положить в отдельный файл.
И да.. У тебе где-то при задании аттрибутов в pug, отсутствует табуляция.

**Comment by clicktronix** [comment]
Т.е. заголовоки без миксинов прописать? а текст вынести наоборот?)

**Comment by shevdi** [comment]
Заголовки можно убрать, но не обязательно. Сделай, как нравится. Но текст точно добавить.

**Comment by clicktronix** [comment]
С текстами разобрался, вынес в отдельные файлики. А табуляцию отсутствующую не нашел, как ты это определил?

**Comment by shevdi** [comment]
Перепутал, в indipixel видел в форме.
