### ISSUE TITLE
Перенести шрифты

### ISSUE THREAD

**Issue by shevdi** [clicktronix/testsummary.github.io#5]
Шрифты все же лучше объявлять в самих блоках, что бы блоки были самодостаточны, что бы при необходимости можно было блок вставить даже в другой проект, не задумываясь, не потерялись ли при этом какие-нибудь стили.
На случай необходимости смены шрифта можно использовать переменные.

**Comment by clicktronix** [comment]
Шрифты перенес, но в переменные их не стал передавать. Вопрос появился, запасные шрифты тоже в переменные передавать? Или их как то отдельно подключать

**Comment by shevdi** [comment]
В переменную можно засунуть прям полное описание шрифта
